### PR TITLE
feat: Add Safety and Security Requirements for Hazard Analysis

### PR DESCRIPTION
**Pull request by lilweege**
# GitHub Ticket / Description

[SS-99](https://github.com/lilweege/SyntaxSentinels/issues/99)

## Type && Checklist

- [x] **New feature (new APIs, new functional methods)**
  - [ ] Created (or updated) unit test cases (if required)
  - [ ] Passed unit testing for **ALL** cases
  - [ ] Created (or updated) E2E cases (if required)
  - [ ] Passed E2E testing for **ALL** cases (local or/and sandbox)
- [ ] **Refactoring / Enhancement**
  - [ ] This is breaking change
  - [ ] Created (or updated) unit test cases (if required)
  - [ ] Passed unit testing for **ALL** cases
  - [ ] Created (or updated) E2E cases (if required)
  - [ ] Passed E2E testing for **ALL** cases (local or/and sandbox)
- [ ] **Bug-fix**
  - [ ] Type:
    - [ ] Code Issue:
    - [ ] Business Logic Issue:
  - [ ] Created (or updated) unit test cases (if required)
  - [ ] Passed unit testing for **ALL** cases
  - [ ] Created (or updated) E2E cases (if required)
  - [ ] Passed E2E testing for **ALL** cases (local or/and sandbox)

## Dependency

[Are there any required updates which cannot be done in this repo, or must be done after completing this PR?]

## Choose proper operation and replace the \<placeholder\>: `+semver:<placeholder>`

`breaking` `major` `feature` `minor` `fix` `patch`

+semver:patch

### CODE REVIEW

**Review by lucasichen — APPROVED** [review]

**Review by N4T10N01 — CHANGES_REQUESTED** [review]
SR-SAF1 -> maybe specify time frame or number of submissions limited to? We can change them later to make them more accurate.

SR-SAF3 -> what is meant by imperfect or potentially?

SR-SAF4 ->second part is rationale, maybe just necessarily to state "system shall validate user submission for code analysis by checking for malformed code" for requirement

SR-SAF5 ->shall be isolated in their host or how so? Maybe run on separate service or something?

**Comment by lilweege** [comment]
I addressed SAF3 and SAF4.
> SR-SAF1 -> maybe specify time frame or number of submissions limited to? We can change them later to make them more accurate.
Do we need to do this for a requirement? This should still be abstract.

> SR-SAF5 ->shall be isolated in their host or how so? Maybe run on separate service or something?
That's an implementation detail.

**Review by N4T10N01 — COMMENTED** [review]
It should still be verifiable and obtainable, saying a specific time frame could be changed to over a user session or maybe over 1 hour etc.

It doesn't have to be solution oriented. Isolated in priority/criticality for example.

**Comment by lilweege** [comment]
Addressed

**Pull request merged**
